"""Add detected_entities to Document

Revision ID: 5c26ed88f378
Revises: 3e83e2b956aa
Create Date: 2026-09-23 20:36:53.386646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c26ed88f378'
down_revision: Union[str, None] = '3e83e2b956aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('detected_entities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'detected_entities')
    # ### end Alembic commands ###
