"""Add detected_entities to Document

Revision ID: 5c26ed88f378
Revises: 3e83e2b956aa
Create Date: 2026-09-23 20:36:53.386646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c26ed88f378'
down_revision: Union[str, None] = '3e83e2b956aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_keys_hash', table_name='api_keys_v2')
    op.drop_index('idx_api_keys_org', table_name='api_keys_v2')
    op.drop_index('idx_api_keys_user', table_name='api_keys_v2')
    op.drop_table('api_keys_v2')
    op.drop_index('idx_usage_date', table_name='api_key_usage')
    op.drop_index('idx_usage_key', table_name='api_key_usage')
    op.drop_table('api_key_usage')
    op.drop_table('login_attempts')
    op.add_column('documents', sa.Column('detected_entities', sa.JSON(), nullable=True))
    op.drop_index('idx_sessions_token', table_name='sessions')
    op.drop_index('idx_sessions_user', table_name='sessions')
    op.drop_index('idx_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_token', 'sessions', ['refresh_token_hash'], unique=False)
    op.drop_column('documents', 'detected_entities')
    op.create_table('login_attempts',
    sa.Column('attempt_id', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('success', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('attempted_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('api_key_usage',
    sa.Column('usage_id', sa.TEXT(), nullable=True),
    sa.Column('key_id', sa.TEXT(), nullable=False),
    sa.Column('endpoint', sa.TEXT(), nullable=False),
    sa.Column('status_code', sa.INTEGER(), server_default=sa.text('(200)'), nullable=True),
    sa.Column('processing_ms', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('entity_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('ip_address', sa.TEXT(), nullable=True),
    sa.Column('used_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys_v2.key_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('idx_usage_key', 'api_key_usage', ['key_id'], unique=False)
    op.create_index('idx_usage_date', 'api_key_usage', ['used_at'], unique=False)
    op.create_table('api_keys_v2',
    sa.Column('key_id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('org_id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('key_hash', sa.TEXT(), nullable=False),
    sa.Column('key_prefix', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('expires_at', sa.TEXT(), nullable=True),
    sa.Column('last_used_at', sa.TEXT(), nullable=True),
    sa.Column('request_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('rate_limit_rpm', sa.INTEGER(), server_default=sa.text('(60)'), nullable=True),
    sa.Column('allowed_endpoints', sa.TEXT(), server_default=sa.text('\'["*"]\''), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_api_keys_user', 'api_keys_v2', ['user_id'], unique=False)
    op.create_index('idx_api_keys_org', 'api_keys_v2', ['org_id'], unique=False)
    op.create_index('idx_api_keys_hash', 'api_keys_v2', ['key_hash'], unique=False)
    # ### end Alembic commands ###
